"""Add password hashing and relationships

Revision ID: 72b0da3b3edc
Revises: bfedac26ed18
Create Date: 2025-02-09 09:29:27.674289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b0da3b3edc'
down_revision = 'bfedac26ed18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['my_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rltobooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rl_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['rl_id'], ['reading_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reading_list')
    with op.batch_alter_table('my_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('my_user', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    op.create_table('reading_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_name', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_chapters', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('chapters_read', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['my_user.id'], name='reading_list_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reading_list_pkey')
    )
    op.drop_table('rltobooks')
    op.drop_table('reading_lists')
    op.drop_table('books')
    # ### end Alembic commands ###
